{
  "name": "Hanet Camera Bridge Pro",
  "version": "2.6.0",
  "slug": "hanet_bridge_pro",
  "description": "Bản quyền bởi trankhanhduy2929-beep",
  "arch": ["aarch64", "amd64", "armv7"],
  "image": "ghcr.io/trankhanhduy2929-beep/hanet_bridge_pro-{arch}"
}
