name: "Hanet Camera Bridge Pro"
description: "Addon này đã được mã hóa bảo mật hoàn toàn."
version: "3.0.0"
slug: "hanet_bridge_pro"
arch:
  - amd64
  - aarch64
  - armv7
# HA sẽ tự động thay {arch} bằng chip máy khách để lấy đúng bản Nuitka đã build
image: "ghcr.io/trankhanhduy2929-beep/my-addon-{arch}"
