{
  "name": "Hanet Camera Bridge",
  "version": "2.5.2",
  "slug": "hanet_bridge",
  "description": "Kết nối Hanet AI Camera qua MQTT và Webhook (Port 2912). Bản LITE",
  "url": "https://github.com/home-assistant/addons/tree/master/mosquitto",
  "arch": ["aarch64", "amd64", "armhf", "armv7", "i386"],
  "startup": "application",
  "boot": "auto",
  "ingress": true,
  "ingress_port": 2912,
  "ports": {
    "2912/tcp": 2912
  },
  "options": {},
  "schema": {}
}
