name: "YouTube Cast Addon Pro"
version: "2.5.0"
slug: "youtube_cast_addon"
description: "Bản quyền bởi trankhanhduy2929-beep. Chạy trực tiếp từ Image bảo mật."
url: "https://github.com/trankhanhduy2929-beep/my_hass_addon_public"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
ingress: true
ingress_port: 2912
# ĐÂY LÀ DÒNG QUAN TRỌNG NHẤT
image: "ghcr.io/trankhanhduy2929-beep/youtube_cast_addon-{arch}"
